### ISSUE TITLE
Why is current step starting from 52745?

### ISSUE THREAD

**Issue by deeperlearner** [daviddirethucus/Face-Mask_Inpainting#5]
In `MaskInpainting_II.ipynb`: `cur_step = 52745`
Why is current step starting from 52745?
`cur_step<3516*6`, for current step < 20k?
How should I change these numbers according to the size of dataset?

**Comment by davidmilsky** [comment]
because i wanna compare diff models at different steps, and also it took long time to run a single epoch. so sequentially save and train the models on diff step. you can just train everything from scratch by setting cur-step=0
